---
title: "Daniel van der Meulen Correspondence Network, 1578-1591"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: https://github.com/jessesadler/dvdm-correspondence/blob/master/dvdm-flexdashboard.Rmd
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(sp)
library(sf)
library(geosphere)
library(leaflet)
library(htmltools)

# Load letters and geographic data
letters <- read_csv("data/letters_id.csv")
locations <- read_csv("data/locations-1591.csv") %>% 
  select(place:lat) # simplify locations data to only necessary variables
routes_sf <- read_rds("data/routes_sf.rds")

# Set baseline for palette to be used for map legend
routes_all <- letters %>% 
  group_by(source, destination) %>%
  summarise(count = n()) %>%
  remove_missing() %>%
  arrange(count)

pal <- colorNumeric(palette = "viridis", domain = routes_all$count, reverse = TRUE)

# Reactive function for filtering letters by date used throughout Shiny app
filtered_letters <- reactive({
  letters[letters$date >= input$range[1] & letters$date <= input$range[2], ]
  })

# Cities: Filtering data for source and destination of correspondence
cities <- reactive({
    
  per_source <- filtered_letters() %>%
    group_by(source) %>%
    rename(place = source) %>% 
    summarise(source = n(),
              correspondents = n_distinct(writer)) %>%
    remove_missing()
  
  per_destination <- filtered_letters() %>%
    group_by(destination) %>%
    rename(place = destination) %>% 
    summarise(destination = n()) %>%
    remove_missing()
  
  # Join geo data to both source and destination, so that cities tibble can
  # have different sets of columns for source and destination.
  # This makes it possible to leaflet draw circles from different sets of information
  geo_per_source <- left_join(per_source, locations, by = "place")
  geo_per_destination <- left_join(per_destination, locations, by = "place")
  
  # Join the geo data frames together
  cities <- full_join(geo_per_source, geo_per_destination, by = "place") %>% 
    replace_na(list(source = 0, destination = 0, correspondents = 0))
  
  return(cities)

  })

# Routes: Filtering data for routes of correspondence and creating great circles for the routes
routes <- reactive({
    
  per_route <- filtered_letters() %>%  
    group_by(id) %>%
    summarise(count = n()) %>%
    remove_missing()
  
  right_join(routes_sf, per_route, by = "id") %>% 
    arrange(count)
    
  })

```

Sidebar {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r slider_input}
sliderInput("range", "Date Range",
           min(as.Date("1578-01-01", "%Y-%m-%d")),
           max(as.Date("1591-12-31", "%Y-%m-%d")),
           value = range(as.Date("1584-08-01", "%Y-%m-%d"), as.Date("1585-12-31", "%Y-%m-%d")),
           timeFormat = "%e %b %Y")
```

This map presents letters received by the 16th-century merchant Daniel van der Meulen from 1578 to the end of 1591. This map is still under development and is part of a larger digital humanities project. The outline of the larger project can be found [here](https://www.jessesadler.com/project/dvdm-correspondence/).

* In order to interact with the map, choose the date range to visualize the letters Daniel van der Meulen received over a specific period.
* Hover over the routes to see the amount of letters sent along each route and the distance of the route. Distance measurements are the shortest geographic distance between the two locations.
* Hover over the cities to see the amount of letters sent from and recieved in the location, as well as the number of correspondents who sent Daniel letters from the location.
* The routes, sources, and destinations objects can all be toggled on or off with the controler on the bottom right of the map.

Application author: [Jesse Sadler](https://www.jessesadler.com)

Comments on the visualization or code are welcome and greatly appreciated. Any comments can be sent to me at: jsadler@ucla.edu, [Twitter](https://twitter.com/vivalosburros), or [ GitHub](https://github.com/jessesadler/dvdm-correspondence)

Row
-----------------------------------------------------------------------

### Map
```{r leaflet_map}
# Base map and legends
output$map <- renderLeaflet({
  leaflet(data = routes_all) %>% addProviderTiles(providers$CartoDB.PositronNoLabels) %>%
    setView(4.8, 49, zoom = 5) %>%
    addLegend(position = "topright",
        colors = c("#ffd24d", "#addd8e"),
        labels = c("Sent Location", "Received Location"),
        opacity = 1) %>%
    addLegend(pal = pal, values = ~count, opacity = 1,
        title = "Letters<br/>Received") %>% 
    addLayersControl(position = "bottomright",
        overlayGroups = c("Destinations", "Sources", "Routes"),
        options = layersControlOptions(collapsed = FALSE))
  })

# CircleMarkers
observe({
  # Return NA for labels if cities function is empty otherwise create labels
  label2 <- if(nrow(cities()) < 1) {
    NA
    } else {
      
    sprintf(
      "<strong>%s</strong><br/>Letters from: %g<br/>Letters to: %g<br/>Correspondents: %g",
      cities()$place, cities()$source, cities()$destination, cities()$correspondents) %>%
      lapply(htmltools::HTML)
    }
    
  leafletProxy("map", data = cities()) %>%
    clearMarkers() %>% 
    addCircleMarkers(lng = ~lon.y, lat = ~lat.y,
        color = "#addd8e", stroke = FALSE, fillOpacity = 1,
        radius = 8,
        group = "Destinations",
        label = label2,
        labelOptions = labelOptions(textsize = "11px")) %>% 
    addCircleMarkers(lng = ~lon.x, lat = ~lat.x,
        color = "#ffd24d", stroke = FALSE, fillOpacity = 1,
        radius = 5,
        group = "Sources",
        label = label2,
        labelOptions = labelOptions(textsize = "11px"))
  })

# Routes
observe({
  # Return NA for labels if routes function is empty otherwise create labels
  label1 <- if(nrow(routes()) < 1) {
    NA
    } else {
      
    sprintf(
      "%s to %s<br/>Distance: %g miles<br/>Letters: %g",
      routes()$source, routes()$destination, routes()$miles, routes()$count) %>%
      lapply(htmltools::HTML)
    }
    
  leafletProxy("map") %>% 
    clearShapes() %>% 
    addPolylines(data = routes(), opacity = 0.9, weight = 3, color = ~pal(count),
        group = "Routes",
        label = label1,
        labelOptions = labelOptions(textsize = "11px"),
        highlight = highlightOptions(weight = 5, color = "red", opacity = 1))
  })

leafletOutput("map")

```