---
title: "Minimal leaflet shiny example"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(leaflet)

# Load letters and geographic data
letters <- read_csv("~/Documents/R/dvdm-correspondence/data/dvdm-correspondence-1591.csv")
locations <- read_csv("~/Documents/R/dvdm-correspondence/data/locations-1591.csv")

# Subset for selected year
  cities <- reactive({
  
    filtered_letters <- letters[letters$year < input$dates, ]
    
    per_source <- filtered_letters %>%
      group_by(source) %>%
      summarise(count = n()) %>%
      remove_missing() %>%
      arrange(count)
    
    cities <- inner_join(locations, per_source, by = c("place" = "source"))
    
    return(cities)
  })  

```

Sidebar {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}
sliderInput("dates", "Date",
            min(1578), max(1592),
            value = 1584, step = 1, sep = "")
```

Choose the date range to visualize the letters received by Daniel van der Meulen. Mouse over the routes to see the amount of letters sent along each route. Mouse over the cities to see the amount of letters sent from and recieved in the location, as well as the number of correspondents who sent Daniel letters from the location.

Row
-----------------------------------------------------------------------

### DvdM correspondence

```{r}
output$map <- renderLeaflet({
    leaflet() %>% addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>%
      setView(3.5, 46.5, zoom = 5)
  })

  # CircleMarkers
  observe({

    leafletProxy("map", data = cities()) %>%
      clearMarkers() %>% 
      addCircleMarkers(lng = ~lon, lat = ~lat,
                       color = "#ffd24d", stroke = FALSE, fillOpacity = 1, radius = 10)
  })

leafletOutput("map")
  
```

