---
title: "Daniel van der Meulen Correspondence"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(sp)
library(sf)
library(geosphere)
library(leaflet)
library(htmltools)
library(RColorBrewer)

# Load letters and geographic data
letters <- read_csv("~/Documents/R/dvdm-correspondence/data/dvdm-correspondence-1591.csv")
locations <- read_csv("~/Documents/R/dvdm-correspondence/data/locations-1591.csv")
geo_data <- select(locations, place:lat) # simplify locations data to only necessary variables
empty_sf <- read_rds("~/Documents/R/dvdm-correspondence/data/empty_sf.rds")

# Set baseline for palette to be used for legend
routes_all <- letters %>% 
  group_by(source, destination) %>%
  summarise(count = n()) %>%
  remove_missing() %>%
  arrange(count)

pal <- colorNumeric(palette = "YlOrRd", domain = routes_all$count)

# Routes: Filtering data for routes of correspondence
  gcircles_routes <- reactive({
    
    filtered_letters <- letters[letters$year >= input$range[1] & letters$year < input$range[2], ]
    
    per_route <- filtered_letters %>%  
      group_by(source, destination) %>%
      summarise(count = n()) %>%
      remove_missing() %>%
      arrange(count) %>% 
      ungroup()
    
    # Skip rest of function and return empty sf lines object if filtered data is empty
    if(nrow(per_route) < 1) {
      empty_sf
    } else {      
      
      # Join data to locations data
      geo_per_route <- per_route %>%
        left_join(geo_data, by = c("source" = "place")) %>% 
        left_join(geo_data, by = c("destination" = "place"))
      geo_per_route$ID <- as.character(c(1:nrow(geo_per_route))) # create id for each pair
      
      source_loc <- select(geo_per_route, lon.x, lat.x)
      dest_loc <- select(geo_per_route, lon.y, lat.y)
      
      # Calculate great circle routes between sources and destinations and return a SpatialLines object
      routes <- gcIntermediate(source_loc, dest_loc, 100, addStartEnd=TRUE, sp=TRUE)
      
      # Convert a SpatialLines object into SpatialLinesDataFrame, so that tabular data can be added
      
      ids <- data.frame()
      
      for (i in (1:length(routes))) {         
        id <- data.frame(routes@lines[[i]]@ID)
        ids <- rbind(ids, id)  }
      
      colnames(ids)[1] <- "ID"
      
      routes <- SpatialLinesDataFrame(routes, data = ids, match.ID = TRUE)
      
      rm(id)
      rm(ids)
      
      # Create and return a SpatialLinesDataFrame
      sp::merge(routes, geo_per_route, by = "ID")
    }
  })

```

Sidebar {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}
sliderInput("range", "Range",
            min(1578), max(1592),
            value = range(1579, 1585), step = 1, sep = "")
```

Choose the date range to visualize the letters received by Daniel van der Meulen. Mouse over the routes to see the amount of letters sent along each route. Mouse over the cities to see the amount of letters sent from and recieved in the location, as well as the number of correspondents who sent Daniel letters from the location.

Row
-----------------------------------------------------------------------

### DvdM correspondence

```{r}
 output$map <- renderLeaflet({
   leaflet(gcircles_routes()) %>% addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>%
      setView(3.5, 46.5, zoom = 5) %>% 
     addPolylines(opacity = 0.9, weight = 3, color = ~pal(count))
   
  })

leafletOutput("map")

```

